name: P & M Outdoor Structures
title: P & M Outdoor Structures
description: >- # this means to ignore newlines until the next yaml key
  Alabama's premiere 
color: "#8a784a"
background_color: "#d0d0d0"
logo: "assets/img/logo.png"
apple_mask_icon: "assets/img/apple-mask-icon.svg"
themed_mask_icon: "assets/img/themed-mask-icon.png"
sharing_image: "assets/photos/woodBuildingsExteriors/redCabin.jpg"
